# Site settings
title: "SPTR"
url: https://sptr.net/
name: SPTR
description: Last in, first out
baseurl: ""

# Build settings
markdown: kramdown
permalink: pretty
highlighter: rouge
paginate: 3

plugins: [jekyll-paginate]

# Links
links:
  - title: "abt"
    url: /about
  - title: "twt"
    url: http://twitter.com/cullaloe
  - title: "git"
    url: http://github.com/cullaloe
  - title: "rss"
    url: /feed.xml

